version: 1
formatters:
  simple:
    format: '%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)'
    datefmt: '%x %I:%M:%S %p'
  basic:
    format: '(%(filename)s:%(lineno)s) ==> %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  sys_err:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: "system.log"
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: "${hydra:job.name}.log"
loggers:
  myLogger:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, sys_err]
