defaults:
  - generation_base_cfg
  - _self_

# The few shotting is specified in this file
# Path is from main dir (above src dir).
few_shot_file: "few_shot_prompts/culture_company/human_annotated_few_shot.txt"

n_generations_per_database: 3

header: "You are given a schema for a SQL dataset.
You should generate a question related to the dataset
and the appropriate SQL query.\n"
table_prefix: "Tables:"
prompt: "Generate a query with multiple tables and a GROUP BY statement."
suffix: "Question:"